"""PCI DSS v4.0 — Technically verifiable control catalog."""

CONTROLS = [
    # Requirement 1: Network Security Controls (8 controls)
    {"control_id": "1.2.1", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "Network security controls (NSCs) are configured and maintained to control inbound and outbound traffic with defined rules for all connections."},
    {"control_id": "1.2.5", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "All services, protocols, and ports allowed are identified, approved, and have a defined business need."},
    {"control_id": "1.2.8", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "Configuration files for NSCs are secured from unauthorized access and kept consistent with active network configurations."},
    {"control_id": "1.3.1", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "Inbound traffic to the cardholder data environment (CDE) is restricted to only necessary and authorized traffic; all other traffic is denied."},
    {"control_id": "1.3.2", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "Outbound traffic from the cardholder data environment (CDE) is restricted to only necessary and authorized traffic; all other traffic is denied."},
    {"control_id": "1.4.1", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "NSCs are implemented between trusted and untrusted networks to control traffic at the network boundary."},
    {"control_id": "1.4.2", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "Inbound traffic from untrusted networks to trusted networks is restricted to communications with system components that are authorized to provide publicly accessible services, protocols, and ports."},
    {"control_id": "1.5.1", "family": "Network Security Controls", "family_id": "NSC",
     "requirement": "Security controls are implemented on any computing devices that connect to both untrusted networks and the CDE to prevent threats from being introduced into the entity's network."},

    # Requirement 2: Secure Configurations (6 controls)
    {"control_id": "2.2.1", "family": "Secure Configurations", "family_id": "SCF",
     "requirement": "System configuration standards are developed, implemented, and kept current; standards are applied before a system is connected to a production environment."},
    {"control_id": "2.2.2", "family": "Secure Configurations", "family_id": "SCF",
     "requirement": "Vendor default accounts are managed as follows: default passwords are changed or accounts are disabled before a system goes into production."},
    {"control_id": "2.2.3", "family": "Secure Configurations", "family_id": "SCF",
     "requirement": "Primary functions requiring different security levels are managed on separate system components, or where co-located, isolated to prevent lower-trust functions from impacting higher-trust functions."},
    {"control_id": "2.2.5", "family": "Secure Configurations", "family_id": "SCF",
     "requirement": "All unnecessary services, protocols, daemons, and functions are removed or disabled; only required functionality is enabled."},
    {"control_id": "2.2.6", "family": "Secure Configurations", "family_id": "SCF",
     "requirement": "System security parameters are configured to prevent misuse and are consistent with system configuration standards."},
    {"control_id": "2.2.7", "family": "Secure Configurations", "family_id": "SCF",
     "requirement": "All non-console administrative access is encrypted using strong cryptography with TLS 1.2 or higher."},

    # Requirement 3: Stored Account Data Protection (10 controls)
    {"control_id": "3.2.1", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Account data storage amount and retention time are limited to that which is required for business, legal, and/or regulatory purposes; data is securely deleted when no longer needed."},
    {"control_id": "3.3.1", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Sensitive authentication data (SAD) is not retained after authorization, including full track data, card verification codes (CAV2/CVC2/CVV2/CID), and PINs/PIN blocks."},
    {"control_id": "3.3.2", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Sensitive authentication data (SAD) is not stored in any electronic format after completion of the authorization process."},
    {"control_id": "3.3.3", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Issuers and companies that support issuing services store sensitive authentication data only with a legitimate issuing business justification and the data is secured."},
    {"control_id": "3.4.1", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "PAN is masked when displayed such that only personnel with a legitimate business need can see more than the first six and last four digits of the PAN."},
    {"control_id": "3.4.2", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "PAN is secured with strong cryptography whenever it is stored, including in portable digital media, backup media, and logs."},
    {"control_id": "3.5.1", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "PAN is rendered unreadable anywhere it is stored by using one-way hashes based on strong cryptography, truncation, index tokens and pads, or strong cryptography with associated key-management processes."},
    {"control_id": "3.5.1.1", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Hashes used to render PAN unreadable are keyed cryptographic hashes of the entire PAN using validated cryptographic key-management processes and procedures."},
    {"control_id": "3.5.1.2", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Disk-level or partition-level encryption is used only to render PAN unreadable on removable electronic media; it is not used for non-removable storage."},
    {"control_id": "3.6.1", "family": "Stored Account Data Protection", "family_id": "SAD",
     "requirement": "Procedures are defined and implemented to protect cryptographic keys used to protect stored account data against disclosure and misuse, including least-privilege access and secure storage."},

    # Requirement 4: Transmission Cryptography (4 controls)
    {"control_id": "4.2.1", "family": "Transmission Cryptography", "family_id": "TXC",
     "requirement": "Strong cryptography and security protocols are implemented to safeguard PAN during transmission over open, public networks, using only trusted keys and certificates."},
    {"control_id": "4.2.1.1", "family": "Transmission Cryptography", "family_id": "TXC",
     "requirement": "Certificates used for PAN transmissions over open, public networks are confirmed as valid and are not expired or revoked."},
    {"control_id": "4.2.1.2", "family": "Transmission Cryptography", "family_id": "TXC",
     "requirement": "Wireless networks transmitting PAN or connected to the cardholder data environment use industry best practices to implement strong cryptography for authentication and transmission."},
    {"control_id": "4.2.2", "family": "Transmission Cryptography", "family_id": "TXC",
     "requirement": "PAN is secured with strong cryptography whenever it is sent via end-user messaging technologies such as email, instant messaging, SMS, and chat."},

    # Requirement 5: Malware Protection (6 controls)
    {"control_id": "5.2.1", "family": "Malware Protection", "family_id": "MAL",
     "requirement": "An anti-malware solution is deployed on all system components, except for those identified as not at risk from malware based on periodic evaluations."},
    {"control_id": "5.2.2", "family": "Malware Protection", "family_id": "MAL",
     "requirement": "The deployed anti-malware solution detects all known types of malware and removes, blocks, or contains all known types of malware."},
    {"control_id": "5.2.3", "family": "Malware Protection", "family_id": "MAL",
     "requirement": "Any system components not protected by anti-malware are evaluated periodically to confirm the components continue to not require anti-malware protection, with risk reassessments documented."},
    {"control_id": "5.3.1", "family": "Malware Protection", "family_id": "MAL",
     "requirement": "The anti-malware solution is kept current via automatic updates from the vendor."},
    {"control_id": "5.3.2", "family": "Malware Protection", "family_id": "MAL",
     "requirement": "The anti-malware solution performs periodic scans and active or real-time scans, with scan frequency defined in the entity's targeted risk analysis."},
    {"control_id": "5.3.3", "family": "Malware Protection", "family_id": "MAL",
     "requirement": "Anti-malware mechanisms and processes are actively running and cannot be disabled or altered by users, unless specifically documented and authorized by management on a case-by-case basis for a limited time period."},

    # Requirement 6: Secure Systems and Software (8 controls)
    {"control_id": "6.2.1", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "Bespoke and custom software are developed securely, consistent with industry standards and/or best practices for secure development."},
    {"control_id": "6.2.2", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "Software development personnel working on bespoke and custom software are trained at least once every 12 months in software security relevant to their job function and development languages."},
    {"control_id": "6.2.3", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "Bespoke and custom software is reviewed prior to being released into production to identify and correct potential coding vulnerabilities, using manual or automated methods."},
    {"control_id": "6.2.4", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "Software engineering techniques or other methods are defined and used by software development personnel to prevent or mitigate common software attacks and related vulnerabilities, including injection, buffer overflow, insecure cryptographic storage, and insecure communications."},
    {"control_id": "6.3.1", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "Security vulnerabilities are identified and managed through a formal process that includes vulnerability risk ranking using industry-recognized frameworks (e.g., CVSS)."},
    {"control_id": "6.3.2", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "An inventory of bespoke and custom software, and third-party software components incorporated into bespoke and custom software, is maintained to facilitate vulnerability and patch management."},
    {"control_id": "6.3.3", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "All system components are protected from known vulnerabilities by installing applicable critical and high-security patches/updates within one month of release."},
    {"control_id": "6.4.1", "family": "Secure Systems and Software", "family_id": "SSS",
     "requirement": "For public-facing web applications, new threats and vulnerabilities are addressed on an ongoing basis, and applications are protected against known attacks using web application firewalls (WAF) or automated vulnerability assessment tools."},

    # Requirement 7: Access Restriction (5 controls)
    {"control_id": "7.2.1", "family": "Access Restriction", "family_id": "ACR",
     "requirement": "An access control model is defined and includes granting access as needed for each role's job classification and function."},
    {"control_id": "7.2.2", "family": "Access Restriction", "family_id": "ACR",
     "requirement": "Access is assigned to users, including privileged users, based on job classification and function with the minimum privileges necessary to perform job responsibilities."},
    {"control_id": "7.2.4", "family": "Access Restriction", "family_id": "ACR",
     "requirement": "All user accounts and related access privileges, including third-party and vendor accounts, are reviewed at least once every six months to ensure appropriateness."},
    {"control_id": "7.2.5", "family": "Access Restriction", "family_id": "ACR",
     "requirement": "All application and system accounts and related access privileges are assigned and managed based on least privilege and reviewed periodically."},
    {"control_id": "7.3.1", "family": "Access Restriction", "family_id": "ACR",
     "requirement": "An access control system is in place that restricts access based on a user's need to know and is set to deny all unless specifically allowed."},

    # Requirement 8: User Authentication (12 controls)
    {"control_id": "8.2.1", "family": "User Authentication", "family_id": "UAT",
     "requirement": "All users are assigned a unique ID before being allowed access to system components or cardholder data."},
    {"control_id": "8.2.2", "family": "User Authentication", "family_id": "UAT",
     "requirement": "Group, shared, or generic accounts, or other shared authentication credentials are only used when necessary on an exception basis and are managed with approval and accountability controls."},
    {"control_id": "8.2.3", "family": "User Authentication", "family_id": "UAT",
     "requirement": "Additional requirement for service providers: service and system accounts used for interactive login are managed based on least privilege and reviewed periodically."},
    {"control_id": "8.2.4", "family": "User Authentication", "family_id": "UAT",
     "requirement": "Addition, deletion, and modification of user IDs, authentication factors, and other identifier objects are managed through a formal process; access is immediately revoked for any terminated user."},
    {"control_id": "8.2.5", "family": "User Authentication", "family_id": "UAT",
     "requirement": "Access for terminated users is immediately revoked, and all physical and logical authentication mechanisms are returned, disabled, or deactivated."},
    {"control_id": "8.2.8", "family": "User Authentication", "family_id": "UAT",
     "requirement": "If a user session has been idle for more than 15 minutes, the user is required to re-authenticate to re-activate the terminal or session."},
    {"control_id": "8.3.1", "family": "User Authentication", "family_id": "UAT",
     "requirement": "All user access to system components for users and administrators is authenticated via at least one of the following: something you know, something you have, or something you are."},
    {"control_id": "8.3.4", "family": "User Authentication", "family_id": "UAT",
     "requirement": "Invalid authentication attempts are limited by locking out the user ID after not more than 10 attempts; lockout duration is a minimum of 30 minutes or until the user's identity is confirmed."},
    {"control_id": "8.3.5", "family": "User Authentication", "family_id": "UAT",
     "requirement": "If passwords/passphrases are used as authentication factors, they are set and reset to a minimum length of 12 characters (or 8 characters if the system does not support 12) containing both numeric and alphabetic characters."},
    {"control_id": "8.3.6", "family": "User Authentication", "family_id": "UAT",
     "requirement": "If passwords/passphrases are used as authentication factors, they are changed at least once every 90 days, or the security posture of accounts is dynamically analyzed and real-time access is automatically determined."},
    {"control_id": "8.3.9", "family": "User Authentication", "family_id": "UAT",
     "requirement": "If passwords/passphrases are used as the only authentication factor for user access, passwords/passphrases are changed at least once every 90 days and are not identical to any of the last four passwords/passphrases used."},
    {"control_id": "8.4.2", "family": "User Authentication", "family_id": "UAT",
     "requirement": "Multi-factor authentication (MFA) is implemented for all access into the cardholder data environment (CDE), using at least two of the three authentication factors."},

    # Requirement 9: Physical Access (5 controls)
    {"control_id": "9.2.4", "family": "Physical Access", "family_id": "PHY",
     "requirement": "Physical access to consoles in sensitive areas is restricted by locking the console when not in use to prevent unauthorized use."},
    {"control_id": "9.4.1", "family": "Physical Access", "family_id": "PHY",
     "requirement": "All media with cardholder data is physically secured, including backup tapes, removable media, paper receipts, and paper reports."},
    {"control_id": "9.4.2", "family": "Physical Access", "family_id": "PHY",
     "requirement": "All media with cardholder data is classified according to the sensitivity of the data so the data can be identified and appropriately protected."},
    {"control_id": "9.4.6", "family": "Physical Access", "family_id": "PHY",
     "requirement": "Hard-copy materials with cardholder data are destroyed when no longer needed for business or legal reasons via cross-cut shredding, incineration, or pulping."},
    {"control_id": "9.4.7", "family": "Physical Access", "family_id": "PHY",
     "requirement": "Electronic media with cardholder data is destroyed when no longer needed for business or legal reasons via secure destruction methods such as secure wiping, degaussing, or physical destruction."},

    # Requirement 10: Logging and Monitoring (8 controls)
    {"control_id": "10.2.1", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit logs are enabled and active for all system components and cardholder data environments to support the detection, alerting, and analysis of events."},
    {"control_id": "10.2.1.1", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit logs capture all individual user access to cardholder data, including read, write, and delete operations."},
    {"control_id": "10.2.1.2", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit logs capture all actions taken by any individual with administrative access, including use of interactive login for application and system accounts."},
    {"control_id": "10.2.1.3", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit logs capture all access to audit logs, including any attempts to read, modify, or delete audit log files."},
    {"control_id": "10.2.1.5", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit logs capture all changes to identification and authentication credentials, including creation of new accounts, elevation of privileges, and all changes, additions, or deletions to accounts with administrative access."},
    {"control_id": "10.2.2", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit logs record at minimum: user identification, type of event, date and time, success or failure indication, origination of event, and identity or name of affected data, system component, resource, or service."},
    {"control_id": "10.3.3", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "Audit log files, including those for external-facing technologies, are promptly backed up to a secure, centralized internal log server(s) or other media that is difficult to alter."},
    {"control_id": "10.6.1", "family": "Logging and Monitoring", "family_id": "LOG",
     "requirement": "System clocks and time are synchronized using time-synchronization technology (e.g., NTP) to one or more designated time servers, and access to time data is restricted to only personnel with a business need."},

    # Requirement 11: Security Testing (6 controls)
    {"control_id": "11.2.1", "family": "Security Testing", "family_id": "TST",
     "requirement": "Authorized and unauthorized wireless access points are managed by generating and maintaining an inventory and performing quarterly wireless scans to detect and identify all wireless access points."},
    {"control_id": "11.3.1", "family": "Security Testing", "family_id": "TST",
     "requirement": "Internal vulnerability scans are performed at least once every three months and after any significant change, with all high-risk and critical vulnerabilities resolved and rescans conducted to confirm resolution."},
    {"control_id": "11.3.2", "family": "Security Testing", "family_id": "TST",
     "requirement": "External vulnerability scans are performed at least once every three months and after any significant change by a PCI SSC Approved Scanning Vendor (ASV), with passing results achieved."},
    {"control_id": "11.4.1", "family": "Security Testing", "family_id": "TST",
     "requirement": "Internal penetration testing is performed at least once every 12 months and after any significant infrastructure or application change, covering the entire CDE perimeter and critical systems."},
    {"control_id": "11.5.1", "family": "Security Testing", "family_id": "TST",
     "requirement": "Network-intrusion detection and/or intrusion-prevention techniques are deployed to detect and/or prevent intrusions into the network, and all traffic at the CDE perimeter and at critical points inside the CDE is monitored."},
    {"control_id": "11.5.2", "family": "Security Testing", "family_id": "TST",
     "requirement": "A change-detection mechanism (for example, file integrity monitoring tools) is deployed to alert personnel to unauthorized modification of critical system files, configuration files, and content files, with comparisons performed at least weekly."},

    # Requirement 12: Organizational Policies (6 controls)
    {"control_id": "12.1.1", "family": "Organizational Policies", "family_id": "ORG",
     "requirement": "An overall information security policy is established, published, maintained, and disseminated to all relevant personnel and to relevant third parties, and reviewed at least once every 12 months."},
    {"control_id": "12.3.1", "family": "Organizational Policies", "family_id": "ORG",
     "requirement": "Each PCI DSS requirement that specifies a periodic activity has a documented targeted risk analysis that defines the frequency of the activity and is reviewed at least annually."},
    {"control_id": "12.6.1", "family": "Organizational Policies", "family_id": "ORG",
     "requirement": "A formal security awareness program is implemented to make all personnel aware of the entity's information security policy and procedures, and their role in protecting cardholder data."},
    {"control_id": "12.6.2", "family": "Organizational Policies", "family_id": "ORG",
     "requirement": "The security awareness program is reviewed at least once every 12 months and updated as needed to address any new threats and vulnerabilities."},
    {"control_id": "12.8.1", "family": "Organizational Policies", "family_id": "ORG",
     "requirement": "A list of all third-party service providers (TPSPs) with which account data is shared or that could affect the security of cardholder data is maintained, including a description of the services provided."},
    {"control_id": "12.10.1", "family": "Organizational Policies", "family_id": "ORG",
     "requirement": "An incident response plan exists and is ready to be activated immediately in the event of a suspected or confirmed security incident, covering roles and responsibilities, communication and contact strategies, and procedures for containment and business continuity."},
]

assert len(CONTROLS) == 84, f"Expected 84 controls, got {len(CONTROLS)}"
